# Feature selecition 

## Point-Biserial Correlation (continuos vs binary)

measure the strength and direction of the association that exists between one **continuous variable** and one **dichotomous variable**. 

 you could use a point-biserial correlation to determine whether there is an association between salaries, measured in US dollars, and gender (i.e., your continuous variable would be "salary" and your dichotomous variable would be "gender", which has two categories: "males" and "females")

Like other correlation coefficients, this one varies between -1 and +1 with 0 implying no correlation. Correlations of -1 or +1 imply a determinative relationship.

In [3]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
Salvar modelo 
https://acervolima.com/salvando-um-modelo-de-aprendizado-de-maquina/

https://deepnote.com/@svpino/A-Scikit-Learn-Pipeline-9b41fc5c-3346-437c-813d-3147eff52a76

In [ ]:
https://machinelearningmastery.com/feature-selection-with-real-and-categorical-data/
https://machinelearningmastery.com/feature-selection-with-categorical-data/

https://www.kaggle.com/code/sathianpong/feature-selection-guide-by-beginner/notebook

In [12]:
data={'gender':[0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
      'salary':[1200, 1400, 1700, 1700, 1100, 2200, 2300, 1100, 1900, 800, 1200]}
df=pd.DataFrame(data)

In [13]:
continue_value = data['salary']
binary_value = data['gender']

In [17]:
stats.pointbiserialr(binary_value, continue_value)

PointbiserialrResult(correlation=0.2181634545788746, pvalue=0.519284292877361)


<span style="color:red">Result</span>

Since the p-value of this correlation is not less than .05, this correlation is not statistically significant. 

Since the correlation coefficient is positive, this indicates that when the variable x takes on the value “1” that the variable y tends to take on higher values compared to when the variable x takes on the value “0.”

https://en.wikipedia.org/wiki/Point-biserial_correlation_coefficient 

In [ ]:
https://towardsdatascience.com/deep-dive-on-ml-techniques-for-feature-selection-in-python-part-1-3574269d5c69

In [ ]:
https://www.kaggle.com/code/guoyiyang92/simple-feature-selection-categorical-continuous
https://en.wikipedia.org/wiki/Correlation_coefficient
https://github.com/otaviosanluz/medium/blob/main/Features-Constantes-QuaseConstantes/01-features-constants-quasiConstants.ipynb

Missing Input

In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder


In [3]:
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


c:\Users\Marcio Rodrigues\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


KNNImputer

In [1]:
from sklearn.impute import KNNImputer

In [2]:
import numpy as np
import pandas as pd
dict = {'First':[100, 90, np.nan, 95], 
        'Second': [30, 45, 56, np.nan], 
        'Third':[np.nan, 40, 80, 98]} 
  
# creating a dataframe from list 
df = pd.DataFrame(dict)

In [3]:
df

First  Second  Third
0  100.0    30.0    NaN
1   90.0    45.0   40.0
2    NaN    56.0   80.0
3   95.0     NaN   98.0

You can define your own n_neighbors value (as its typical of KNN algorithm).

In [4]:
imputer = KNNImputer(n_neighbors=2)

In [5]:
df_filled = imputer.fit_transform(df)

In [7]:
df_filled

array([[100. ,  30. ,  69. ],
       [ 90. ,  45. ,  40. ],
       [ 97.5,  56. ,  80. ],
       [ 95. ,  43. ,  98. ]])

In [9]:
df_filled

array([[100. ,  30. ,  69. ],
       [ 90. ,  45. ,  40. ],
       [ 97.5,  56. ,  80. ],
       [ 95. ,  43. ,  98. ]])

In [14]:
tes = df_filled[0:1]

In [15]:
tes

array([[100.,  30.,  69.]])

In [22]:
tes

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [20]:
tes.reshape(-1, 1)

array([[100.],
       [ 30.],
       [ 69.]])

In [12]:
df_filled

array([[100. ,  30. ,  69. ],
       [ 90. ,  45. ,  40. ],
       [ 97.5,  56. ,  80. ],
       [ 95. ,  43. ,  98. ]])

In [1]:
from sklearn.impute import KNNImputer

In [4]:
train = pd.read_csv("data/census - Copy.csv")

In [5]:
imputer = KNNImputer(n_neighbors=3)

In [6]:
var = train['age'].to_numpy()

In [7]:
var = var.reshape(-1, 1)

In [8]:
fille = imputer.fit_transform(var)

In [9]:
train['age_2'] = fille

In [10]:
train.head()

age          workclass  final-weight   education  education-num  \
0  39.0          State-gov         77516   Bachelors             13   
1  50.0   Self-emp-not-inc         83311   Bachelors             13   
2  38.0            Private        215646     HS-grad              9   
3   NaN            Private        234721        11th              7   
4  28.0            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  \
0          2174             0             40   United-States   <=50K   
1             0             0             13   United-States   <=50K   
2             0             0             40   United-States   <=50K   
3             0             0             40   United-States   <=50K   
4             0             0             40            Cuba   <=50K   

       age_2  
0  39.000000  
1  50.000000  
2  38.000000  
3  38.411765  
4  28.000000

In [12]:
train[train['age'].isna()].head()

age   workclass  final-weight      education  education-num  \
3   NaN     Private        234721           11th              7   
5   NaN     Private        284582        Masters             14   
25  NaN   Local-gov        216851      Bachelors             13   
26  NaN     Private        168294        HS-grad              9   
27  NaN           ?        180211   Some-college             10   

         marital-status          occupation relationship                 race  \
3    Married-civ-spouse   Handlers-cleaners      Husband                Black   
5    Married-civ-spouse     Exec-managerial         Wife                White   
25   Married-civ-spouse        Tech-support      Husband                White   
26        Never-married        Craft-repair    Own-child                White   
27   Married-civ-spouse                   ?      Husband   Asian-Pac-Islander   

        sex  capital-gain  capital-loos  hour-per-week  native-country  \
3      Male             0             0             40   United-States   
5    Female             0             0             40   United-States   
25     Male             0             0             40   United-States   
26     Male             0             0             40   United-States   
27     Male             0             0             60           South   

    income      age_2  
3    <=50K  38.411765  
5    <=50K  38.411765  
25    >50K  38.411765  
26   <=50K  38.411765  
27    >50K  38.411765

In [52]:
feature_store =  pd.read_parquet("data/feature_bogota.parquet")

In [53]:
len(feature_store)

8543

In [54]:
var = feature_store['average_rating'].to_numpy()

In [55]:
var = var.reshape(-1, 1)

In [56]:
imputer = KNNImputer(n_neighbors=5)

In [57]:
fille = imputer.fit_transform(var)

In [ ]:
https://medium.com/@ning.jia/5-approaches-to-impute-missing-data-in-time-series-d6c75227819b